"""Regenerate docs/DATA_MODEL.md from the field lists the pipeline actually uses.

Run after adding or changing a table:

    python tools/gen_data_model.py

Columns come from the FIELDS constants in the code, so the document cannot drift
from the schema. Descriptions live in DESCRIPTIONS below — add a line when you
add a table.
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from etl.load import (coaches, leadership, performance, pipeline,  # noqa: E402
                      profiles, resilience, style)
from etl.load.formations import FORMATION_FIELDS  # noqa: E402
from etl.parsers.statistics import VALUE_COLS  # noqa: E402
from etl.transform import (appearances, incidents, penalties,  # noqa: E402
                           players, teamstats, timeline, youth)
from etl.transform.clubform import CLUB_FORM_FIELDS  # noqa: E402

STAGING = [
    ("players.csv", "player", players.PLAYER_FIELDS,
     "Registry: one row per player, with identity, verified club and activity status."),
    ("callups.csv", "player x call-up window", players.CALLUP_FIELDS,
     "Squad lists: who was named, with their club and caps at that moment."),
    ("appearances.csv", "player x match", appearances.APPEARANCE_FIELDS
     + timeline.PRESENCE_FIELDS,
     "Per-match performance, plus the reconstructed presence window."),
    ("events.csv", "match (with lineups)", appearances.EVENT_FIELDS,
     "Match dimension for player analysis: score, formations, stats coverage."),
    ("match_states.csv", "match", timeline.STATE_FIELDS,
     "Rebuilt match clock: goal bins, minutes leading/level/trailing, comeback flags."),
    ("goal_events.csv", "goal", incidents.GOAL_FIELDS + timeline.GOAL_EXTRA_FIELDS,
     "Every goal with running score, clock position and what it changed."),
    ("substitutions.csv", "substitution", incidents.SUB_FIELDS,
     "Substitutions with minute and injury flag."),
    ("cards.csv", "card", incidents.CARD_FIELDS, "Cards with minute and reason."),
    ("injury_times.csv", "period end", incidents.INJURY_FIELDS,
     "Announced stoppage-time length per period."),
    ("concessions.csv", "goal conceded", timeline.CONCESSION_FIELDS,
     "Each goal conceded with the deficit it created and the reply that followed."),
    ("penalties.csv", "penalty attempt", penalties.PENALTY_FIELDS,
     "In-game and shootout penalties, per taker."),
    ("shootouts_alltime.csv", "shootout", penalties.SHOOTOUT_FIELDS,
     "All-time shootout record (martj42)."),
    ("team_match_stats.csv", "match x period x side", teamstats.STATS_FIELDS,
     "Team statistics for Burkina Faso and the opponent (ALL / 1st / 2nd half)."),
    ("youth_callups.csv", "player x youth squad", youth.YOUTH_FIELDS,
     "U-17/U-20 squad lists linked to the senior registry."),
    ("club_form.csv", "player", CLUB_FORM_FIELDS,
     "Latest club season per active player (apps, minutes, rating)."),
]

MARTS = [
    ("player_profile.csv", "player", profiles.PROFILE_FIELDS,
     "Per-player aggregates over the study window plus identity and club form."),
    ("player_importance.csv", "player", performance.IMPORTANCE_FIELDS,
     "Gated importance components and the Pillar/Rotation/Fringe tier."),
    ("bench_impact.csv", "player", performance.BENCH_FIELDS,
     "Substitute output, entry minute and game state at entry."),
    ("team_timeline.csv", "15-minute bin", performance.TIMELINE_FIELDS,
     "Goals for and against per period, with the stoppage-time share."),
    ("formations.csv", "formation", FORMATION_FIELDS,
     "Record per starting formation with average opponent Elo."),
    ("team_style.csv", "scope x side x axis", style.STYLE_FIELDS,
     "Style axes overall, by year, by opponent-Elo tercile and by formation."),
    ("resilience.csv", "metric x scope", resilience.RESILIENCE_FIELDS,
     "Deficit ladder, reply behaviour, output by game state, late swing."),
    ("clutch_players.csv", "player", resilience.CLUTCH_FIELDS,
     "Goals classified by what they changed, per player."),
    ("captains.csv", "captain", leadership.CAPTAIN_FIELDS,
     "Record with the armband."),
    ("goalkeepers.csv", "goalkeeper", leadership.GK_FIELDS,
     "Goalkeeper comparison: goals conceded on pitch, saves, clean sheets."),
    ("coach_eras.csv", "tenure", coaches.ERA_FIELDS,
     "Record per head-coach tenure, with the Elo swing."),
    ("pipeline.csv", "youth cohort", pipeline.COHORT_FIELDS,
     "Squad size, graduations and median time to a senior debut."),
]

HEADER = """# Data model

Generated by `python tools/gen_data_model.py` — do not edit by hand. Column lists
come from the field constants in the code, so this file cannot drift from the
schema.

Layers: `data/raw/` (immutable source snapshots, gitignored) →
`data/staging/` (typed, clean tables) → `data/marts/` (analysis-ready) and
`site/data/*.json` (what the dashboard fetches). See
[ARCHITECTURE.md](ARCHITECTURE.md).
"""


def table_block(title, tables):
    out = [f"\n## {title}\n"]
    for name, grain, fields, doc in tables:
        out.append(f"\n### `{name}`\n")
        out.append(f"\n{doc}\n")
        out.append(f"\n- **Grain**: one row per {grain}\n")
        out.append(f"- **Columns** ({len(fields)}): "
                   + ", ".join(f"`{f}`" for f in fields) + "\n")
    return "".join(out)


def main():
    body = [HEADER, table_block("Staging tables", STAGING),
            table_block("Marts", MARTS)]
    body.append("\n## Statistics value columns\n")
    body.append("\nThe per-match statistics parser emits these columns for each side "
                "(absent when the source omits them):\n\n")
    body.append(", ".join(f"`{c}`" for c in VALUE_COLS) + "\n")
    dest = ROOT / "docs" / "DATA_MODEL.md"
    dest.parent.mkdir(exist_ok=True)
    dest.write_text("".join(body), encoding="utf-8")
    n_cols = sum(len(f) for _, _, f, _ in STAGING + MARTS)
    print(f"wrote {dest} ({len(STAGING)} staging tables, {len(MARTS)} marts, "
          f"{n_cols} columns documented)")


if __name__ == "__main__":
    main()
